---
- name: This playbook is to copy a file from this server to all nodes
  hosts: all
  become: true
  tasks:
  - name: copying a file
    copy:
      src: /home/ansadmin/index.html
      dest: /home/ansadmin
      mode: 0600
      owner: akash
