---
- name: this playbook install httpd, start its service and copy index.html file to designated location
  hosts: all
  become: true
  tasks:
  - name: to install httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: to start httpd
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: to install apache2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: to start apache2
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: to copy index.html file to another location
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html/index.html
      mode: 0666
