---
- name: this playbook is to install httpd package and start it service
  hosts: all
  become: yes
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
    notify: start httpd service

  handlers:
  - name: start httpd service
    service:
      name: httpd
      state: started
