
---
- name: this playbook is to install webpackagie and handle error
  hosts: all
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: start httpd service
    service:
      name: http-- # Giving bug intentionally
      state: started
    when: ansible_os_family == "RedHat"
    ignore_errors: yes

  - name: install apache 2
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: start apache2 service
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copy index.html
    copy:
      src: /home/ansadmin/index.html
      dest: /var/www/html
      mode: 0666

