---
- name: this playbook is to setup tomcat
  hosts: all
  become: yes
  tasks:
  - name: install java on redhat
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: install java on debian
    apt:
      name: Open JDK
      state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat package
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.90/bin/apache-tomcat-9.0.90.tar.gz
      dest: /opt

  - name: extract tomcat package
    unarchive:
      src: /opt/apache-tomcat-9.0.90.tar.gz
      dest: /opt
      remote_src: yes

  - name: giving executable permission to startup.sh file
    file:
      path: /opt/apache-tomcat-9.0.90/bin/startup.sh
      mode: 0777

  - name: start tomcat service
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-9.0.90/bin
